apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-completion-server
  namespace: "costrict" # 命名空间
spec:
  replicas: 1 # 设置数量
  selector:
    matchLabels:
      app: code-completion
  template:
    metadata:
      labels:
        app: code-completion
    spec:
      containers:
      - name: code-completion-container
        image: ""
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 4Gi
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        env:
          - name: THRESHOLD_SCORE
            value: "0.3"
          - name: MAIN_MODEL_TYPE
            value: "openai"
          - name: MAX_MODEL_LEN
            value: "5000,1000"  # 注意：类型为字符串
          - name: OPENAI_MODEL_HOST
            value: ""  # 补全接口
          - name: OPENAI_MODEL
            value: "DeepSeek-Coder-V2-Lite-Base"  # 模型名称
          - name: OPENAI_MODEL_AUTHORIZATION
            value: ""  # 模型认证key可选
          - name: CODEBASE_DEFINITION_URL
            value: "http://codebase-indexer-svc.shenma.svc.cluster.local:8888/codebase-indexer/api/v1/search/definition" # 定义检索地址
          - name: CODEBASE_SEMANTIC_URL
            value: "http://codebase-indexer-svc.shenma.svc.cluster.local:8888/codebase-embedder/api/v1/search/semantic" # 语义检索地址
          - name: CODEBASE_SEMANTIC_TOP_K
            value: "5"
          - name: CODEBASE_SEMANTIC_SCORE_THRESHOLD
            value: "0.5"
          - name: CONTEXT_COST_TIME # 上下文最长处理请求时间 ms
            value: "1700"
          - name: CONTEXT_REQUEST_TIMEOUT # 上下文最长请求时间 ms
            value: "1000"
          - name: MAX_TOKENS
            value: "500"
          - name: MAX_MODEL_COST_TIME
            value: "2800"
          - name: MAX_COST_TIME
            value: "3000"
          - name: MULTI_LINE_STREAM_K
            value: "8"
          - name: MIN_PREFIX_TOKEN
            value: "2000"
            # redis配置
          - name: ENABLE_REDIS
            value: "False"
          - name: REDIS_HOST
            value: ""
          - name: REDIS_PORT
            value: ""
          - name: REDIS_DB
            value: ""
          - name: REDIS_PWD
            value: ""
          - name: COMPLETION_CACHE_TIME
            value: "86400"
          - name: CONTINUE_COMPLETION_CACHE_EXPIRED
            value: "30"


---
apiVersion: v1
kind: Service
metadata:
  name: code-completion-svc
  namespace: "costrict" # 命名空间
spec:
  type: ClusterIP
  selector:
    app: code-completion
  ports:
    - protocol: TCP
      port: 5000         # 集群内访问使用的端口
      targetPort: 5000 # 转发到 Pod 的容器端口
  
  
---
# Horizontal Pod Autoscaler 配置
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: code-completion-hpa
  namespace: "costrict" # 命名空间
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: code-completion-server
  minReplicas: 1 # 最小副本数
  maxReplicas: 9 # 最大副本数（水平扩容上限）
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80 # CPU 使用率目标 70%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 # 内存使用率目标 80%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60 # 扩容稳定窗口时间
      policies:
      - type: Percent
        value: 50 # 每次最多增加 50% 的副本数
        periodSeconds: 60
      - type: Pods
        value: 2 # 每次最多增加 2 个副本
        periodSeconds: 60
      selectPolicy: Max # 选择较大的策略
    scaleDown:
      stabilizationWindowSeconds: 300 # 缩容稳定窗口时间（5分钟）
      policies:
      - type: Percent
        value: 30 # 每次最多减少 10% 的副本数
        periodSeconds: 60
      - type: Pods
        value: 2 # 每次最多减少 1 个副本
        periodSeconds: 60
      selectPolicy: Min # 选择较小的策略
